# source: http://rosettacode.org/wiki/Send_an_email#Python

import smtplib

from mail_settings import *

GMAILSMTP = 'smtp.gmail.com:587'

def sendemail(subject, message, smtpserver=GMAILSMTP):
    to_addr_list = ['a@vlabs.ac.in', 'chandan@vlabs.ac.in', 'dp@vlabs.ac.in']
    header  = 'From: %s\n' % FROM_ADDR
    header += 'To: %s\n' % ','.join(to_addr_list)
    header += 'Subject: %s\n\n' % subject
    message = header + message
 
    server = smtplib.SMTP(smtpserver)
    server.starttls()
    server.login(LOGIN,PASSWORD)
    problems = server.sendmail(FROM_ADDR, to_addr_list, message)
    server.quit()
    return problems

def mailer(start_time, end_time, elapsed_time, errors_count, errors):
    template = """
Summary
=======

Start time: %s
End time: %s
Elaspsed time: %s
Errors encountered: %s

________________________________________________________________________________

Error details
=============
%s
________________________________________________________________________________

This is an automated email generated by SIMO (syncing & mirroring of svn, git and 
bzr repos to Bitbucket). SIMO sources are hosted at https://github.com/vlead/simo

""" % (start_time, end_time, elapsed_time, errors_count, errors)
    sendemail("SIMO log report for %s" % start_time[:11], template)
