# source: http://rosettacode.org/wiki/Send_an_email#Python

import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from mail_settings import *

def sendemail(subject, message, smtpserver=SMTPSERVER, attachment=None):
    msg = MIMEMultipart()
    msg['Subject'] = subject
    msg['From'] = FROM_ADDR
    msg['To'] = ",".join(TO_ADDR_LIST)
    msgbody = MIMEText(message)
    msg.attach(msgbody)
 
    if attachment:
        msg_attachment = MIMEText(open(attachment, 'rb').read())
        msg_attachment.add_header('Content-Disposition', 'attachment', 
                                    filename=attachment.split("/")[-1])
        msg.attach(msg_attachment)

    server = smtplib.SMTP(SMTPSERVER)
    server.starttls()
    server.login(LOGIN,PASSWORD)
    problems = server.sendmail(FROM_ADDR, TO_ADDR_LIST, msg.as_string())
    server.quit()
    return problems

def mailer(start_time, end_time, elapsed_time, errors_count, errors, log_file=None):
    template = """
Summary
=======

Start time: %s
End time: %s
Elaspsed time: %s
Errors encountered: %s

________________________________________________________________________________

Error details
=============
%s
________________________________________________________________________________

This is an automated email generated by SIMO (syncing & mirroring of svn, git and 
bzr repos to Bitbucket). SIMO sources are hosted at https://github.com/vlead/simo

""" % (start_time, end_time, elapsed_time, errors_count, errors)
    sendemail("SIMO log report for %s" % start_time[:11], template, attachment=log_file)
